#!/bin/bash
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# gitconfig
ln -s ${BASEDIR}/gitconfig/gitconfig ~/.gitconfig
ln -s ${BASEDIR}/gitconfig/gitignore ~/.gitignore

# ntp.br
sudo bash ${BASEDIR}/ntp/install.sh

# homesbrew
bash ${BASEDIR}/homebrew/install.sh

#Terraform modules
ln -s ${BASEDIR}/terraform/terraformrc ~/.terraformrc

#Google Cloud SDK components
bash ${BASEDIR}/gcloud/install.sh

# vimfiles
mkdir -p ~/.config
ln -s ${BASEDIR}/vim/vimrc ~/.vimrc
ln -s ${BASEDIR}/vim/ ~/.vim
ln -s ${BASEDIR}/vim/ ~/.config/nvim
vim +PlugInstall +qa!

# Set osx defaults
bash ${BASEDIR}/osx-defaults/set-defaults.sh

# Configuring ssh
sudo rm /etc/ssh/ssh_config
sudo cp ${BASEDIR}/ssh/ssh_config /etc/ssh/ssh_config

# iTerm2
rm ~/Library/Preferences/com.googlecode.iterm2.plist
ln -s ${BASEDIR}/iterm2/com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist

# Installing NERDFonts
wgeti https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/SourceCodePro/Regular/complete/Sauce%20Code%20Pro%20Nerd%20Font%20Complete.ttf?raw=true -O  ~/Library/Fonts/Sauce\ Code\ Pro\ Nerd\ Font\ Complete.ttf

# Installing oh-my-zsh
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
chsh -s /bin/zsh
