#!/bin/bash
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Install packages
bash ${BASEDIR}/apt/install.sh

# Setup git
ln -s ${BASEDIR}/git/gitconfig ~/.gitconfig

# Setup gnupg
ln -s ${BASEDIR}/gnupg/gpg.conf ~/.gnupg/gpg.conf
ln -s ${BASEDIR}/gnupg/gpg-agent.conf ~/.gnupg/gpg-agent.conf

# Go get packages
bash ${BASEDIR}/golang/install.sh

# Configure Alacritty
ln -s ${BASEDIR}/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml

# Configuring ssh
mkdir -p ${BASEDIR}/.ssh/
ln -s ${BASEDIR}/ssh/config \
	~/.ssh/config

# Setup tmux
ln -s ${BASEDIR}/tmux/tmux.conf ~/.tmux.conf

# Setup kubectl plugins & addons
mv /usr/local/bin/kubens /usr/local/bin/knamespace
mv /usr/local/bin/kubectx /usr/local/bin/kcontext

# vimfiles
mkdir -p ~/.config
ln -s ${BASEDIR}/nvim/ ~/.config/
curl -fLo ${BASEDIR}/nvim/autoload/plug.vim --create-dirs \
	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim +PlugInstall +qall

# Create secrets file
touch ${BASEDIR}/.secrets

# Configure helm
helm plugin install https://github.com/futuresimple/helm-secrets

# Configure tarsnap
mkdir ~/.tarsnap/
mkdir ~/.tarsnap/logs
mkdir ~/.tarsnap/cache
touch ~/.tarsnap/tarsnap.key
ln -s ${BASEDIR}/tarsnap/tarsnaprc ~/.tarsnaprc
launchctl load ~/.dotfiles/tarsnap/tarsnap.plist

# Setup bash_profile
rm ~/.profile
rm ~/.zshrc
ln -s ${BASEDIR}/zsh/zshrc ~/.zshrc
