let $nvim_tui_enable_true_color=1
set background=dark
set hlsearch
set incsearch
set smartcase
set noshowmode
set t_Co=256
set t_ut=
set t_vb=""
set visualbell
set cursorline
set colorcolumn=80
set clipboard=unnamed
set number
set hidden
set list
set listchars=eol:¬
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
set lazyredraw
set ttyfast
set scrolloff=27
set sidescrolloff=27
set sidescroll=1
syntax on
syntax enable
colorscheme dracula
