export ZSH=$HOME/.oh-my-zsh

#ZSH_THEME="bureau-lucazz"
ZSH_THEME="node"

plugins=(docker docker-compose pip python vagrant)

source $ZSH/oh-my-zsh.sh
source $HOME/.dotfiles/credentials


if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

alias vim="nvim"

export AUTO_MOUNT_HOME=false
export GOPATH="/Users/Lucas/Projects/Golang"
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export PATH="/usr/local/sbin:$PATH"
export VAGRANT_DEFAULT_PROVIDER="vmware_fusion"

#Auto jump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
