export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="lucazz"

plugins=(docker docker-compose pip python vagrant)

source $ZSH/oh-my-zsh.sh
source $HOME/.dotfiles/credentials


if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

alias vim="nvim"
alias pip-update="pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U"

export ANSIBLE_VAULT_PASSWORD_FILE="~/.ansible/vaultpw"
export ANSIBLE_CONFIG="~/.ansible/ansible.cfg"
export AUTO_MOUNT_HOME=false
export GOPATH="/Users/lucazz/Projects/Golang"
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_CASK_OPTS=--require-sha
