export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

plugins=(git)

source $ZSH/oh-my-zsh.sh
source $HOME/.dotfiles/credentials


if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

alias vim="nvim"

export ANSIBLE_CONFIG="/Users/lucazz/.ansible/ansible.cfg"
