# Source all secrets
source ~/.secrets

# Source all exports
source ~/.dotfiles/zsh/exports.zsh

# Source all zsh configs
source ~/.dotfiles/zsh/config.zsh

# Source all aliases
source ~/.dotfiles/zsh/aliases.zsh

# initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
compinit
autoload -U +X bashcompinit && bashcompinit
source ~/.dotfiles/zsh/completion.zsh
source ~/.dotfiles/zsh/plugins/kubectl.zsh

# Enable autojump
source /usr/local/etc/profile.d/autojump.sh

# Enable git prompt
source ~/.dotfiles/zsh/plugins/git.zsh

# Enable ASDF
. "$(brew --prefix asdf)/asdf.sh"

# Enable direnv
eval "$(direnv hook zsh)"

# Enable FZF
source ~/.fzf.zsh

# Enable tmux
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_AUTOSTART_ONCE=true
ZSH_TMUX_AUTOQUIT=true
ZSH_TMUX_AUTOCONNECT=true
source ~/.dotfiles/zsh/plugins/tmux.zsh
