for file in $HOME/.dotfiles/bash/*.d;
do
	source $file
done

source ~/.secrets

#Auto jump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# Bash completion
[ -f /usr/local/etc/bash_completion.d ] && . /usr/local/etc/bash_completion.d
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

#Prompt
PS1="\[$(tput setaf 2)\]\W \[\033[33m\]\$(parse_git_branch)\[\033[00m\]\$\[$(tput sgr0)\\[$(tput sgr0)\] "

tmux attach

cd
